### ISSUE TITLE
tickFormat() renders 50 as "5e+1" with some format specifiers

### ISSUE THREAD

**Issue by adamhooper** [d3/d3-scale#169]
```
> const d3scale = require('d3-scale')
> d3scale.tickFormat(0, 100, 3, ',')(50)
```

Expected result: `50`
Actual result: `5e+1`

Ditto for `""`, `","`, `"g"`, `".2"`.

I don't think this is intentional. The only reason `test/linear-test.js` passes these tests is that the number being formatted is 2 (as opposed to, say, 20):

```javascript
tape("linear.tickFormat(count, specifier) sets the appropriate round precision if not specified", function(test) {
  test.equal(scale.scaleLinear().domain([0, 9]).tickFormat(10, "")(2.10), "2");
  test.equal(scale.scaleLinear().domain([0, 9]).tickFormat(100, "")(2.01), "2");
  test.equal(scale.scaleLinear().domain([0, 9]).tickFormat(100, "")(2.11), "2.1");
  ...
```

As a test, I changed the first line to `test.equal(scale.scaleLinear().domain([0, 90]).tickFormat(10, "")(21.0), "20");`. (By my reading of the docs and tests, this should pass.) Failure:

```
# linear.tickFormat(count, specifier) sets the appropriate round precision if not specified
not ok 442 should be equal
  ---
    operator: equal
    expected: '20'
    actual:   '2e+1'
    at: Test.<anonymous> (/home/adam/src/upstream/d3-scale/test/linear-test.js:413:8)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (/home/adam/src/upstream/d3-scale/node_modules/tape/lib/test.js:226:54)
          at Test.bound [as _assert] (/home/adam/src/upstream/d3-scale/node_modules/tape/lib/test.js:77:32)
          at Test.equal (/home/adam/src/upstream/d3-scale/node_modules/tape/lib/test.js:386:10)
          at Test.bound [as equal] (/home/adam/src/upstream/d3-scale/node_modules/tape/lib/test.js:77:32)
          at Test.<anonymous> (/home/adam/src/upstream/d3-scale/test/linear-test.js:413:8)
          at Test.bound [as _cb] (/home/adam/src/upstream/d3-scale/node_modules/tape/lib/test.js:77:32)
          at Test.run (/home/adam/src/upstream/d3-scale/node_modules/tape/lib/test.js:96:10)
          at Test.bound [as run] (/home/adam/src/upstream/d3-scale/node_modules/tape/lib/test.js:77:32)
          at Immediate.next [as _onImmediate] (/home/adam/src/upstream/d3-scale/node_modules/tape/lib/results.js:75:19)
          at runCallback (timers.js:705:18)
  ...
```

**Comment by mbostock** [comment]
This is intentional. The scale’s tick format will render ticks using a precision based on the tick step. Per [d3-format](https://github.com/d3/d3-format/blob/master/README.md#locale_format), the format types `​`, `e`, `g`, `r`, `s` and `p` interpret the precision as the number of significant digits. In the examples above, the precision is 1 because it only requires one significant digit to disambiguate the ticks. If you don’t want significant digits precision, you should use `f` instead.
